// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['module', 'odo/express', 'odo/durandal'], function(module, express, durandal) {
    var Welcome;
    return Welcome = (function() {
      function Welcome() {
        this.web = __bind(this.web, this);
      }

      Welcome.prototype.web = function() {
        express.route('/views', express.modulepath(module.uri) + '/public');
        return durandal.register('views/welcome');
      };

      return Welcome;

    })();
  });

}).call(this);
