// Generated by CoffeeScript 1.7.1
(function() {
  var requirejs;

  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {
      odo: './node_modules/odo',
      local: './'
    }
  });

  requirejs(['odo/bootstrap']);

}).call(this);
