// Generated by CoffeeScript 1.7.1
(function() {
  var requirejs,
    __slice = [].slice;

  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {
      odo: './node_modules/odo',
      local: './'
    }
  });

  process.env.PORT = 1234;

  requirejs(['odo/plugins', 'odo/express/plugin', 'odo/bower/plugin', 'odo/durandal/plugin', 'odo/messaging/plugin', 'odo/public/plugin', 'local/welcome/plugin'], function() {
    var Express, Plugins, plugins;
    Plugins = arguments[0], Express = arguments[1], plugins = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    new Plugins(plugins).web();
    return new Express().start();
  });

}).call(this);
